

/*TemMailAntet*/
INSERT INTO [TemMailAntet] ([Id],[Ad],[Icerik]) VALUES (1,N'Default',N'<div style="display:inline-block;border:1px solid gainsboro;"><div style="border-bottom:1px solid gainsboro;"><a href="https://app.nftcreator.click"><img src="https://app.nftcreator.click/img/mail/header.png" alt="" width="925" /></a></div><div style="border-bottom:1px solid gainsboro;"><div style="padding:30px 15px;"><p>[#AntetContent#]</p></div></div><div><a href="https://app.nftcreator.click"><img src="https://app.nftcreator.click/img/mail/footer.png" alt="" width="925" /></a></div></div>');

/*TemMailSablon*/
INSERT INTO [TemMailSablon] ([Id],[AntetId],[Alan],[Konu],[Icerik]) VALUES (101, 1, N'', N'Password notification.', N'<p><span style="font-size:xx-large;">PASSWORD NOTIFICATION</span><br /><span style="font-size:x-small;"></span><span style="font-size:small;"></span><span style="font-size:medium;"></span></p><p style="text-align:justify;"><span style="font-size:large;">Your new password has been created.<br /></span></p><table style="width:810px;"><tbody><tr><td style="width:155px;"><span style="font-size:large;"><strong>User name</strong></span></td><td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#Kullanici_Ad#]</span></td></tr><tr><td style="width:155px;"><span style="font-size:large;"><strong>Password</strong></span></td><td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#Kullanici_Sifre#]</span></td></tr></tbody></table><p><span style="font-size:large;"><em><br />Do not forget to change your password at certain time intervals.</em></span></p><p><em><span style="font-size:large;">&nbsp;</span></em></p>');
INSERT INTO [TemMailSablon] ([Id],[AntetId],[Alan],[Konu],[Icerik]) VALUES (102, 1, N'', N'Membership confirmation notice.', N'<p><br /><span style="font-size:large;"></span></p><p style="text-align:justify;"><span style="font-size:large;">Dear [#AdSoyad#], </span></p><p style="text-align:justify;"><span style="font-size:large;">Your membership request has been received, you must confirm it from the link below for your membership to be active.</span></p><p>&nbsp;</p><p><a href="[#OnayLinkHostAddress#]/Account/UyeKayitOnay?prms=[#OnayLinkValue#]" target="_blank"><span>[#OnayLinkText#]</span></a></p><p>&nbsp;</p><p><span style="font-size:large;"><em>If you are not making this request, ignore it.</em></span></p><p><span style="font-size:large;"><em></em> </span></p>');


